# Generated by Django 5.0.2 on 2024-02-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('checked', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Med', 'Med'), ('High', 'High')], max_length=6)),
                ('time', models.SmallIntegerField(null=True)),
                ('on_time', models.BooleanField(null=True)),
            ],
        ),
    ]
