# Generated by Django 5.0.2 on 2024-02-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_remove_todo_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
