# Generated by Django 5.0.2 on 2024-02-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_todo_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='checked_at',
            field=models.DateTimeField(null=True),
        ),
    ]
