# Generated by Django 5.0.2 on 2024-02-15 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_todo_checked_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='todo',
            name='due_date',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todo.taskdates'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='taskdates',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name=' user_date_tasks_constraint'),
        ),
    ]
