# Generated by Django 5.0.2 on 2024-02-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_taskdates_todo_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdates',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
