# Generated by Django 5.0.2 on 2024-02-18 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_alter_taskdates_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_tasks', to='todo.taskdates'),
        ),
    ]
