# Generated by Django 5.0.2 on 2024-02-19 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0015_alter_todo_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='priority',
            new_name='piriority',
        ),
    ]
